#!/bin/bash

set -e

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi

if [ -f "$1" ]; then
    CONFIG="$1"
    shift
else
    CONFIG="root.conf.yaml"
fi

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

#echo "Updating dotbot..."
cd "${BASEDIR}"
#git submodule update --init --recursive --remote

echo "Running dotbot..."
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"