#!/usr/bin/env bash

set -e

if [ -f "$1" ]; then
    CONFIG="$1"
elif [ -z "$1" ]; then
    echo "Usage: install [config] <dotbot_options>"
    exit 1
else
    echo "Configuration not found: $1"
    exit 1
fi
shift

DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"