#!/bin/env zsh

# start compton
compton -b --config ~/.config/compton/compton.conf

# bsp config
bspc config border_width 1
bspc config window_gap  12

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc monitor DVI-D-0 -d I
bspc monitor DVI-I-0 -d II

# rules
bspc rule -a Chromium desktop=I
bspc rule -a Steam desktop=II
bspc rule -a Pidgin desktop=X

bspc config external_rules_command=./bsp_erules

# launch stuff
{
  # wait for an internet connection
  while ! wget http://google.com -O- 2>/dev/null | grep -q Lucky; do
    sleep .1
  done

  # launch stuff
  chromium &
  steam &
  pidgin &
} &

{
  ~/.term/bsp_init_term.zsh &
} &
