#!/bin/sh

# start compton
compton -b --config ~/.config/compton/compton.conf

# bsp config
bspc config border_width 1
bspc config window_gap  12

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc monitor DVI-D-0 -d I
bspc monitor DVI-I-0 -d II
