---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
    - direction: Vertical
      body: true

tabs:
  - name: "Term"
    focus: true
  - name: "Files"
    parts:
      - direction: Vertical 
        run:
          command: { cmd: ranger }

session:
  name: "main"
  attach: true