#!/bin/env zsh

# bsp config
bspc config border_width 1
bspc config window_gap  12
bspc config top_padding 20

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config initial_polarity second_child


# Make desktops
_WM_MONITORS=("${(@f)$(xrandr --listactivemonitors | tail -n +2 | awk '{print $4}')}")
_DESKTOPS=(1 2 3 4 5)

for m in $_WM_MONITORS; do
  bspc monitor "$m" -d "${_DESKTOPS[@]/%/_$m}"
done 

# rules
#bspc rule -a Chromium desktop=I
#bspc rule -a Firefox desktop=I
#bspc rule -a Steam desktop=II
#bspc rule -a Pidgin desktop=X

# bspc config external_rules_command=./bsp_erules

# start compton
compton -b

# launch stuff
#{
  # wait for an internet connection
#  while ! wget http://google.com -O- 2>/dev/null | grep -q Lucky; do
#    sleep .2
#  done

  # launch stuff
  #chromium &
  #firefox &
  #vivaldi-snapshot &
#  pidgin &
#  steam -silent &

#} &


# {
#  sleep 3
#  ~/.term/bsp_init_term.zsh &
# } &

# panel
yabar &


#disown
